/* CLIENTA QA pass 16: Referest-inspired searchable design discovery. */
(function(){
const KEYWORDS={
0:'dark black premium luxury classic minimal',1:'blue clean corporate modern minimal',2:'green eco organic natural clean',3:'warm beige editorial classic serif premium',4:'purple violet creative digital',5:'yellow bold brutal festival',6:'cyan tech neon digital',7:'white clean minimal corporate',8:'orange energetic commerce',9:'red bold contrast',
10:'luxury black gold premium dark',11:'editorial ivory beige classic serif',12:'pearl beauty soft light',13:'noir editorial dark premium',14:'champagne luxury warm premium',15:'neo blue saas corporate app',16:'lime bold app tech',17:'cloud clean minimal corporate',18:'pill app cards rounded',19:'midnight gradient dark tech',20:'blush beauty pink soft',21:'milk rose beauty soft pink',22:'lavender beauty wellness soft',23:'beauty editorial beige luxury',24:'mono minimal white swiss',25:'track automotive dark sport',26:'carbon automotive dark industrial',27:'electric automotive tech neon',28:'titanium automotive industrial clean',29:'racing red automotive sport dark',30:'clinic medical clean white',31:'calm blue medical corporate',32:'mint care medical wellness green',33:'dental pearl medical clean',34:'clinical mono medical minimal',35:'bistro food restaurant warm',36:'olive food organic restaurant',37:'wine restaurant luxury dark',38:'cafe cream food warm editorial',39:'sushi dark food restaurant japanese',40:'brutalist brutal bold yellow',41:'creative violet agency creative',42:'sunset creative warm coral',43:'orbital tech dark digital',44:'swiss typography minimal corporate'
};
const NICHE={
'Барбершоп':['dark','premium','editorial','minimal'],'Салон красоты':['beauty','soft','editorial','luxury'],'Маникюр':['beauty','pink','soft','minimal'],'Брови и ресницы':['beauty','soft','luxury'],'Массаж':['wellness','organic','soft','minimal'],'Косметология':['beauty','medical','clean','premium'],'Клиника':['medical','clean','corporate','minimal'],'Стоматология':['medical','clean','white','minimal'],'Психолог':['wellness','soft','editorial','clean'],'Остеопат':['medical','wellness','clean'],
'Автосервис':['automotive','industrial','dark','sport'],'Детейлинг':['automotive','premium','dark','tech'],'Шиномонтаж':['automotive','industrial','sport'],'Автомойка':['automotive','clean','tech'],'Тюнинг-ателье':['automotive','dark','sport','neon'],
'Ресторан':['restaurant','food','editorial','luxury'],'Кафе':['cafe','food','warm','organic'],'Кондитерская':['food','soft','pink','editorial'],'Доставка еды':['food','app','cards','bold'],
'Фитнес-клуб':['sport','dark','bold','app'],'Йога-студия':['wellness','organic','soft','editorial'],'Персональный тренер':['sport','bold','dark'],'Танцевальная студия':['creative','bold','festival'],
'Клининг':['clean','minimal','corporate'],'Ремонт квартир':['industrial','corporate','minimal'],'Дизайн интерьера':['editorial','luxury','minimal','typography'],'Мебель на заказ':['editorial','warm','minimal','premium'],
'Онлайн-школа':['education','app','corporate','cards'],'Репетитор':['education','clean','soft'],'Языковая школа':['education','app','corporate'],'Автошкола':['education','automotive','corporate'],
'Груминг':['soft','organic','cards'],'Ветклиника':['medical','soft','clean'],'Передержка':['soft','organic','warm'],
'Фотограф':['portfolio','editorial','typography','minimal'],'Видеограф':['portfolio','dark','creative','editorial'],'Юрист':['corporate','classic','minimal','premium'],'Бухгалтер':['corporate','clean','minimal'],'Маркетинговое агентство':['agency','creative','brutal','typography'],'IT-студия':['tech','saas','dark','brutal'],'Риелтор':['realty','luxury','corporate','editorial'],'Аренда апартаментов':['travel','luxury','editorial','warm']};
const SYN={
'премиум':'premium luxury','дорогой':'premium luxury','люкс':'luxury premium','минимализм':'minimal clean','минималистичный':'minimal clean','темный':'dark black','тёмный':'dark black','светлый':'white light clean','черный':'black dark','чёрный':'black dark','белый':'white clean','яркий':'bold creative','брутальный':'brutal bold','классика':'classic editorial','классический':'classic editorial','современный':'modern app','технологичный':'tech digital','неон':'neon tech','натуральный':'organic natural','эко':'organic natural','медицинский':'medical clean','авто':'automotive sport','ресторан':'restaurant food','кафе':'cafe food','красивый':'premium editorial','женственный':'beauty soft','розовый':'pink beauty','строгий':'corporate minimal','корпоративный':'corporate clean','карточный':'cards app','типографика':'typography editorial','портфолио':'portfolio editorial','агентство':'agency creative','сайт':'modern','приложение':'app cards'};
function words(q){q=(q||'').toLowerCase().replace(/[.,/#!$%^&*;:{}=\-_`~()]/g,' ');Object.entries(SYN).forEach(([a,b])=>{if(q.includes(a))q+=' '+b});return q.split(/\s+/).filter(Boolean)}
function score(i,q,biz){const hay=(KEYWORDS[i]||'')+' '+((NICHE[biz]||[]).join(' '));return words(q).reduce((s,w)=>s+(hay.includes(w)?3:0),0)+(NICHE[biz]||[]).reduce((s,w)=>s+((KEYWORDS[i]||'').includes(w)?1:0),0)}
function enhance(){const box=document.getElementById('themes');if(!box||box.dataset.searchReady)return;box.dataset.searchReady='1';const wrap=document.createElement('div');wrap.className='designFinder';wrap.innerHTML='<div class="designFinderTitle"><b>Найти стиль</b><small>Например: «тёмный премиум», «минимализм», «яркий», «как luxury ресторан»</small></div><div class="designSearchRow"><input id="designSearch" class="field" placeholder="Поиск по стилю, настроению или ключевым словам"><button id="designReset" type="button">Все</button></div><div id="designQuick" class="designQuick"></div><div id="designCount" class="designCount"></div>';box.parentNode.insertBefore(wrap,box);
const quick=['Премиум','Минимализм','Тёмный','Светлый','Яркий','Классика','Tech','Editorial','Карточный','Organic'];document.getElementById('designQuick').innerHTML=quick.map(x=>`<button type="button" data-dq="${x}">${x}</button>`).join('');
function filter(q=''){const cards=[...box.querySelectorAll('.theme')];const ranked=cards.map((el,i)=>({el,i,s:score(i,q,st?.biz)}));ranked.forEach(x=>{x.el.dataset.designKeywords=KEYWORDS[x.i]||'';x.el.style.display=(!q||x.s>0)?'':'none'});if(q)ranked.sort((a,b)=>b.s-a.s).forEach(x=>{if(x.s>0)box.appendChild(x.el)});const visible=ranked.filter(x=>!q||x.s>0).length;document.getElementById('designCount').textContent=q?`Найдено вариантов: ${visible}`:`Все стили · рекомендуемые для «${st?.biz||'бизнеса'}» отмечены сверху`;}
const inp=document.getElementById('designSearch');inp.addEventListener('input',()=>filter(inp.value));document.getElementById('designReset').onclick=()=>{inp.value='';filter('')};document.getElementById('designQuick').onclick=e=>{const b=e.target.closest('[data-dq]');if(!b)return;inp.value=b.dataset.dq;filter(inp.value)};filter('');}
function sortRecommended(){const box=document.getElementById('themes');if(!box)return;const cards=[...box.querySelectorAll('.theme')];cards.sort((a,b)=>(b.classList.contains('industryTop')?1:0)-(a.classList.contains('industryTop')?1:0)).forEach(x=>box.appendChild(x));}
['heroCreate','newBtn','smartStart'].forEach(id=>document.getElementById(id)?.addEventListener('click',()=>setTimeout(()=>{enhance();sortRecommended()},80)));document.getElementById('bizGrid')?.addEventListener('click',()=>setTimeout(()=>{enhance();sortRecommended();const x=document.getElementById('designSearch');if(x)x.dispatchEvent(new Event('input'))},100));setTimeout(()=>{enhance();sortRecommended()},400);
const css=document.createElement('style');css.textContent='.designFinder{margin:10px 0 14px;padding:14px;border:1px solid #ddd;border-radius:20px;background:#fff}.designFinderTitle{display:flex;justify-content:space-between;gap:12px;align-items:baseline}.designFinderTitle b{font-size:16px}.designFinderTitle small{color:#777;text-align:right}.designSearchRow{display:flex;gap:8px;margin-top:10px}.designSearchRow .field{margin:0;min-width:0}.designSearchRow button,.designQuick button{border:1px solid #ddd;background:#f7f7f7;border-radius:999px;padding:9px 12px;font-weight:700}.designQuick{display:flex;gap:6px;overflow:auto;padding:9px 0 2px;scrollbar-width:none}.designQuick button{white-space:nowrap;font-size:11px}.designCount{font-size:11px;color:#777;margin-top:8px}@media(max-width:520px){.designFinderTitle{display:block}.designFinderTitle small{display:block;text-align:left;margin-top:3px}.designSearchRow{align-items:stretch}.designSearchRow input{font-size:16px}}';document.head.appendChild(css);
window.CLIENTA_DESIGN_SEARCH={keywords:KEYWORDS,niches:NICHE,score};
})();