/* CLIENTA QA pass 16: original responsive reference library. No copied screenshots/assets. */
(function(){
const ARCH=[
['Editorial','editorial magazine typography luxury serif',0,'editorial'],['Swiss','minimal swiss clean grid corporate',1,'swiss'],['Bento','bento cards saas product app',2,'bento'],['Immersive','immersive portfolio visual premium fullbleed',3,'immersive'],['Split','split asymmetric modern conversion',4,'split'],['Catalog','catalog list ecommerce services clean',5,'catalog'],['Performance','automotive sport dark technical',6,'performance'],['Glass','glass tech gradient futuristic digital',7,'glass'],['Brutal','brutal bold typography experimental agency',8,'brutal'],['Compact','compact app mobile utility dense',9,'compact'],['Gallery','gallery portfolio fashion architecture image-led',3,'gallery'],['Story','storytelling warm hospitality lifestyle editorial',0,'story']
];
const MOOD=[
['Obsidian','dark black luxury premium',10,9],['Ivory','ivory beige premium warm',11,10],['Pearl','white soft beauty clean',12,10],['Noir','dark editorial mono premium',13,9],['Champagne','warm gold luxury refined',14,9],['Neo','blue modern product tech',15,5],['Lime','bold lime energetic tech',16,15],['Cloud','clean white corporate minimal',17,5],['Midnight','dark gradient digital tech',19,8],['Blush','pink beauty soft feminine',20,10],['Carbon','automotive industrial dark',26,5],['Wine','restaurant hospitality dark warm',37,9]
];
const NICHES={
'Автосервис':'performance carbon swiss catalog dark technical','Детейлинг':'performance carbon immersive luxury dark','Шиномонтаж':'performance catalog brutal technical','Автомойка':'compact neo clean performance','Тюнинг-ателье':'performance immersive brutal dark neon',
'Барбершоп':'editorial noir luxury brutal dark','Салон красоты':'editorial pearl blush luxury gallery','Маникюр':'pearl blush gallery soft beauty','Брови и ресницы':'pearl blush editorial beauty','Массаж':'story pearl warm soft wellness','Косметология':'pearl swiss clean beauty medical','Клиника':'swiss cloud clean medical corporate','Стоматология':'swiss pearl cloud medical clean','Психолог':'story editorial pearl soft calm','Остеопат':'swiss story clean wellness',
'Фитнес-клуб':'performance brutal compact dark sport','Йога-студия':'story pearl ivory soft wellness','Персональный тренер':'performance brutal compact sport','Танцевальная студия':'brutal immersive gallery energetic',
'Ресторан':'story editorial wine ivory hospitality','Кафе':'story editorial ivory warm hospitality','Кондитерская':'gallery blush pearl story food','Доставка еды':'compact bento catalog product food',
'Клининг':'swiss cloud catalog clean corporate','Ремонт квартир':'catalog swiss performance industrial','Дизайн интерьера':'gallery editorial swiss luxury architecture','Мебель на заказ':'gallery story editorial warm premium',
'Онлайн-школа':'bento compact neo swiss education','Репетитор':'swiss story pearl clean education','Языковая школа':'bento compact swiss education','Автошкола':'compact performance swiss education',
'Груминг':'gallery pearl blush compact playful','Ветклиника':'swiss pearl cloud clean medical','Передержка':'story gallery pearl warm pets',
'Фотограф':'gallery immersive editorial noir portfolio','Видеограф':'immersive noir brutal gallery portfolio','Юрист':'swiss editorial obsidian corporate premium','Бухгалтер':'swiss cloud catalog corporate clean','Маркетинговое агентство':'brutal immersive bento glass agency','IT-студия':'bento glass compact midnight tech','Риелтор':'gallery editorial ivory swiss luxury','Аренда апартаментов':'gallery story ivory editorial hospitality'
};
const SYN={'лакшери':'luxury premium','люкс':'luxury premium','дорогой':'luxury premium','тёмный':'dark noir black','темный':'dark noir black','светлый':'white clean ivory pearl','минимализм':'minimal swiss clean','минималистичный':'minimal swiss clean','брутальный':'brutal bold','современный':'modern neo product','технологичный':'tech digital glass','карточный':'cards bento app','журнальный':'editorial magazine','портфолио':'gallery immersive portfolio','уютный':'warm story ivory','женственный':'beauty blush pearl','медицинский':'medical clean swiss','авто':'automotive performance carbon','ресторан':'restaurant hospitality story','сайт':'web modern','приложение':'app compact'};
const refs=[];let id=0;ARCH.forEach((a,ai)=>MOOD.forEach((m,mi)=>refs.push({id:id++,name:`${m[0]} ${a[0]}`,tags:`${a[1]} ${m[1]}`,layout:a[2],dna:a[3],theme:m[2],font:m[3]})));
function norm(q=''){q=q.toLowerCase();Object.entries(SYN).forEach(([a,b])=>{if(q.includes(a))q+=' '+b});return q.replace(/[^a-zа-яё0-9 ]/gi,' ').split(/\s+/).filter(Boolean)}
function score(r,q,biz){const ws=norm(q),n=(NICHES[biz]||'');const hay=(r.name+' '+r.tags+' '+r.dna).toLowerCase();let s=0;ws.forEach(w=>{if(hay.includes(w))s+=5;if(n.includes(w))s+=2});n.split(' ').forEach(w=>{if(hay.includes(w))s+=1});return s}
function isTop(r,biz){return score(r,'',biz)>=3||norm(NICHES[biz]||'').some(w=>(r.tags+' '+r.dna).includes(w))}
let oldNorm=typeof normalizeProject==='function'?normalizeProject:null;if(oldNorm){normalizeProject=function(p={}){const n=oldNorm(p);n.refStyle=p.refStyle||p.referenceStyle||'';return n}}
let oldClient=typeof clientMarkup==='function'?clientMarkup:null;if(oldClient){clientMarkup=function(input,interactive=true){const p=normalizeProject(input);let h=oldClient(p,interactive);const r=refs.find(x=>x.name===p.refStyle);if(r)h=h.replace('class="public','class="public ref-'+r.dna+' ref-'+(r.id%6));return h}}
function apply(r){if(typeof st==='undefined')return;st.layout=r.layout;st.theme=r.theme;st.font=r.font;st.refStyle=r.name;try{renderThemes?.();renderFonts?.();renderPreview?.()}catch(e){}document.querySelectorAll('.refCard').forEach(x=>x.classList.toggle('selected',x.dataset.id==r.id))}
function mount(){const themes=document.getElementById('themes');if(!themes||document.getElementById('originalRefLibrary'))return;const s=document.createElement('section');s.id='originalRefLibrary';s.className='originalRefs';s.innerHTML=`<div class="refHead"><div><b>Авторские дизайн-референсы</b><small>${refs.length} адаптивных направлений · телефон / планшет / ноутбук / desktop</small></div><button id="refRecommended" type="button">Лучшие для ниши</button></div><input id="refQuery" class="field" placeholder="Поиск: luxury dark, минимализм, bento, editorial, авто, beauty…"><div id="refTags" class="refTags"></div><div id="refCount" class="refCount"></div><div id="refCards" class="refCards"></div>`;themes.parentNode.insertBefore(s,themes);const tags=['Все','Luxury','Minimal','Dark','Editorial','Bento','Gallery','Tech','Brutal','Beauty','Medical','Auto','Food','Corporate'];document.getElementById('refTags').innerHTML=tags.map(x=>`<button type="button" data-q="${x==='Все'?'':x.toLowerCase()}">${x}</button>`).join('');let q='',onlyTop=false;function draw(){const biz=st?.biz||'';let arr=refs.map(r=>({r,s:score(r,q,biz)})).filter(x=>(!q||x.s>0)&&(!onlyTop||isTop(x.r,biz)));arr.sort((a,b)=>(isTop(b.r,biz)?1:0)-(isTop(a.r,biz)?1:0)||b.s-a.s);document.getElementById('refCount').textContent=`${arr.length} вариантов${biz?' · '+biz:''}`;document.getElementById('refCards').innerHTML=arr.map(({r})=>`<button type="button" class="refCard ${isTop(r,biz)?'top':''} ${st?.refStyle===r.name?'selected':''}" data-id="${r.id}"><i class="refMini ref-${r.dna} ref-${r.id%6}"><em></em><em></em><em></em><em></em></i><b>${r.name}</b><small>${r.tags.split(' ').slice(0,5).join(' · ')}</small>${isTop(r,biz)?'<span>РЕКОМЕНДУЕМ</span>':''}</button>`).join('');document.querySelectorAll('.refCard').forEach(b=>b.onclick=()=>apply(refs[+b.dataset.id]))}
const inp=document.getElementById('refQuery');inp.oninput=()=>{q=inp.value.trim();onlyTop=false;draw()};document.getElementById('refRecommended').onclick=()=>{onlyTop=!onlyTop;draw()};document.getElementById('refTags').onclick=e=>{const b=e.target.closest('[data-q]');if(!b)return;q=b.dataset.q;inp.value=q;onlyTop=false;draw()};draw()}
const css=document.createElement('style');css.textContent=`
.originalRefs{margin:14px 0 20px;padding:14px;border:1px solid #dedede;border-radius:22px;background:#fff}.refHead{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.refHead b{display:block;font:800 17px/1.15 Arial}.refHead small{display:block;color:#777;margin-top:4px;max-width:420px}.refHead button,.refTags button{border:1px solid #ddd;background:#f7f7f7;border-radius:999px;padding:9px 11px;font-weight:750}.refTags{display:flex;gap:7px;overflow:auto;padding:10px 0 4px;scrollbar-width:none}.refTags button{white-space:nowrap;font-size:11px}.refCount{font-size:11px;color:#777;margin:8px 0}.refCards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;max-height:620px;overflow:auto;padding-right:2px}.refCard{position:relative;text-align:left;border:1px solid #ddd;background:#fff;border-radius:18px;padding:10px;min-width:0}.refCard.top{box-shadow:inset 0 0 0 2px #111}.refCard.selected{outline:3px solid #315cff}.refCard>b{display:block;font-size:14px;margin-top:9px}.refCard>small{display:block;color:#777;font-size:10px;margin-top:4px}.refCard>span{position:absolute;right:7px;top:7px;background:#111;color:#fff;font:800 7px Arial;border-radius:99px;padding:5px}.refMini{height:92px;display:grid;grid-template-columns:1fr 1fr;grid-template-rows:1.2fr 1fr;gap:4px;padding:7px;border-radius:12px;background:linear-gradient(135deg,#111,#444);overflow:hidden}.refMini em{display:block;background:#fff;border-radius:6px;opacity:.92}.ref-editorial em:first-child,.ref-story em:first-child,.ref-immersive em:first-child,.ref-gallery em:first-child{grid-column:1/-1}.ref-bento em:first-child{grid-row:1/-1}.ref-swiss{background:#f3f3ef}.ref-swiss em{background:#111;border-radius:1px}.ref-glass{background:linear-gradient(135deg,#5b5cff,#ff77c8)}.ref-glass em{opacity:.45;backdrop-filter:blur(8px)}.ref-brutal{background:#e9ff3f}.ref-brutal em{background:#111;border-radius:0}.ref-performance{background:#0a0b0c}.ref-performance em{background:linear-gradient(135deg,#222,#d9ff45);border-radius:2px}.ref-compact{grid-template-columns:repeat(3,1fr);grid-template-rows:repeat(2,1fr)}.ref-catalog{display:flex;flex-direction:column}.ref-catalog em{height:17px;border-radius:2px}.ref-split em:first-child{grid-row:1/-1}.ref-gallery{grid-template-columns:1.4fr .6fr}.ref-story{background:linear-gradient(135deg,#b48b67,#f3e9dc)}
.public[class*="ref-"]{--refGap:14px}.public.ref-editorial .publicHero{background:transparent!important;color:var(--ptxt)!important;border-top:1px solid var(--pline);border-bottom:1px solid var(--pline);border-radius:0!important}.public.ref-editorial .publicHero h1{font-size:clamp(40px,10vw,72px);line-height:.92}.public.ref-swiss .service,.public.ref-swiss .feature,.public.ref-swiss .quick{border-radius:0!important;box-shadow:none!important}.public.ref-swiss h2{text-transform:uppercase;letter-spacing:.12em;font-size:12px}.public.ref-bento .services,.public.ref-bento .features{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.public.ref-bento .service:nth-child(3n+1){grid-column:span 2}.public.ref-immersive .publicHero{min-height:52vh;display:flex;flex-direction:column;justify-content:flex-end}.public.ref-immersive .services{display:flex;overflow:auto;scroll-snap-type:x mandatory;gap:12px}.public.ref-immersive .service{min-width:78%;scroll-snap-align:start}.public.ref-split .publicHero{display:grid;grid-template-columns:1.2fr .8fr;gap:16px;align-items:end}.public.ref-split .publicBtn{grid-column:2}.public.ref-catalog .service{border-radius:0!important;border-width:0 0 1px!important;background:transparent!important;padding:16px 2px!important}.public.ref-performance .publicHero{clip-path:polygon(0 0,95% 0,100% 18%,100% 100%,5% 100%,0 82%)}.public.ref-performance .service{border-left:4px solid var(--pac);border-radius:4px!important}.public.ref-glass .publicHero,.public.ref-glass .service,.public.ref-glass .feature{backdrop-filter:blur(18px);box-shadow:inset 0 1px #fff5,0 18px 45px #0002}.public.ref-brutal .publicHero,.public.ref-brutal .service,.public.ref-brutal .feature{border:2px solid var(--ptxt)!important;border-radius:0!important;box-shadow:5px 5px 0 var(--ptxt)!important}.public.ref-compact .services,.public.ref-compact .features{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.public.ref-compact .service,.public.ref-compact .feature{padding:11px!important}.public.ref-gallery .services{display:grid;grid-template-columns:1.3fr .7fr;gap:10px}.public.ref-gallery .service:nth-child(3n+1){grid-row:span 2;min-height:180px}.public.ref-story .publicHero{min-height:300px;display:flex;flex-direction:column;justify-content:flex-end;background:linear-gradient(160deg,var(--pac),color-mix(in srgb,var(--pac) 25%,var(--pbg)))!important}
@media(max-width:900px){.refCards{grid-template-columns:repeat(2,minmax(0,1fr))}.public.ref-split .publicHero{grid-template-columns:1fr}.public.ref-split .publicBtn{grid-column:auto}}
@media(max-width:520px){.originalRefs{padding:11px;border-radius:18px}.refHead{display:block}.refHead button{margin-top:9px}.refCards{grid-template-columns:1fr;max-height:520px}.refMini{height:84px}.public.ref-bento .services,.public.ref-bento .features,.public.ref-compact .services,.public.ref-compact .features,.public.ref-gallery .services{grid-template-columns:1fr}.public.ref-bento .service:nth-child(3n+1),.public.ref-gallery .service:nth-child(3n+1){grid-column:auto;grid-row:auto;min-height:auto}.public.ref-immersive .service{min-width:86%}.public.ref-story .publicHero{min-height:240px}}
`;document.head.appendChild(css);
['heroCreate','newBtn','smartStart'].forEach(id=>document.getElementById(id)?.addEventListener('click',()=>setTimeout(mount,80)));document.getElementById('bizGrid')?.addEventListener('click',()=>setTimeout(mount,100));setTimeout(mount,300);window.CLIENTA_ORIGINAL_REFERENCES=refs;
})();