/* CLIENTA QA pass 19: first-time-user visual design chooser */
(function(){
function enhance(){
 const root=document.getElementById('catalog7500'); if(!root||root.dataset.visual==='1')return; root.dataset.visual='1';
 const head=root.querySelector('.c75Head'); if(head){head.innerHTML='<div><b>Выберите, как будет выглядеть приложение</b><small>Нажмите на вариант — справа сразу увидите настоящий интерфейс. Цвета, шрифты и расположение блоков уже входят в каждый стиль.</small></div><span id="c75Count">7 500</span>';}
 const search=document.getElementById('c75Search'); if(search)search.placeholder='Например: чёрный премиум, светлый минимализм, авто, beauty…';
 const q=document.getElementById('c75Quick'); if(q){q.insertAdjacentHTML('beforebegin','<div class="c75Guide"><b>Не знаете, что выбрать?</b><span>Начните с «ТОП для ниши» — мы покажем подходящие варианты для вашего бизнеса.</span></div>');}
 const obs=new MutationObserver(()=>decorate()); const grid=document.getElementById('c75Grid'); if(grid)obs.observe(grid,{childList:true}); decorate();
}
function decorate(){document.querySelectorAll('.c75Card').forEach(card=>{if(card.dataset.viz)return;card.dataset.viz='1';const id=+card.dataset.id;const x=window.CLIENTA_7500?.preset?.(id);if(!x)return;const sw=card.querySelector('.sw');if(sw){sw.className='sw c75Visual';sw.innerHTML='<i></i><i></i><i></i><i></i><i></i>';}
 const b=card.querySelector('b'); const sm=card.querySelector('small'); if(b)b.textContent=x.arch[0]+' — '+x.pal[0];if(sm){const tone=toneText(x.pal[1]),layout=layoutText(x.arch[1]);sm.innerHTML='<strong>'+tone+'</strong><span>'+layout+'</span><span>Шрифт: '+x.type[0]+'</span>';}
});}
function toneText(t){t=t.toLowerCase();if(t.includes('dark')||t.includes('black')||t.includes('noir'))return 'Тёмные тона · контрастный';if(t.includes('beauty')||t.includes('pink')||t.includes('rose'))return 'Мягкие светлые тона';if(t.includes('medical')||t.includes('white')||t.includes('blue'))return 'Светлые чистые тона';if(t.includes('warm')||t.includes('ivory')||t.includes('cream'))return 'Тёплые спокойные тона';if(t.includes('neon')||t.includes('lime'))return 'Яркий акцент · тёмная база';return 'Светлый нейтральный стиль';}
function layoutText(t){t=t.toLowerCase();if(t.includes('bento')||t.includes('cards'))return 'Карточная композиция';if(t.includes('gallery')||t.includes('portfolio'))return 'Визуальная галерея';if(t.includes('editorial')||t.includes('magazine'))return 'Журнальная композиция';if(t.includes('catalog'))return 'Каталог услуг';if(t.includes('dashboard'))return 'Панель с данными';if(t.includes('immersive')||t.includes('story'))return 'Большие визуальные блоки';if(t.includes('brutal')||t.includes('bold'))return 'Крупная типографика';return 'Чистая универсальная сетка';}
const css=document.createElement('style');css.textContent=`
#catalog7500{padding:18px;border-radius:24px;background:#f7f6f2;border:1px solid #dedbd3}.c75Head{align-items:flex-start!important}.c75Head>div{max-width:560px}.c75Head b{font-size:24px!important;line-height:1.05}.c75Head small{font-size:13px!important;line-height:1.45;color:#666!important}.c75Guide{display:flex;gap:8px;align-items:center;padding:11px 13px;margin-top:10px;border-radius:14px;background:#111;color:#fff;font-size:12px}.c75Guide span{opacity:.72}.c75Card{padding:10px!important;min-height:220px!important;display:flex;flex-direction:column}.c75Visual{width:100%!important;height:112px!important;border-radius:12px!important;margin:0 0 12px!important;padding:9px;display:grid!important;grid-template-columns:1.3fr .7fr;grid-template-rows:1.15fr .85fr;gap:5px;background:linear-gradient(135deg,var(--c),color-mix(in srgb,var(--c) 18%,#f4f1ea))!important}.c75Visual i{display:block;background:#fff;border-radius:5px;opacity:.9}.c75Visual i:first-child{grid-row:1/-1}.c75Visual i:nth-child(4),.c75Visual i:nth-child(5){display:none}.c75Card:nth-child(3n+2) .c75Visual{grid-template-columns:1fr 1fr;grid-template-rows:1.2fr .8fr}.c75Card:nth-child(3n+2) .c75Visual i:first-child{grid-row:auto;grid-column:1/-1}.c75Card:nth-child(3n) .c75Visual{display:flex!important;flex-direction:column}.c75Card:nth-child(3n) .c75Visual i{height:22px}.c75Card>b{font-size:15px!important}.c75Card small{display:flex!important;flex-direction:column;gap:3px;margin-top:7px!important}.c75Card small strong{font-size:11px;color:#222}.c75Card small span{font-size:10px;color:#777}.c75Card.sel{outline:3px solid #3487ff!important;box-shadow:0 10px 30px #0001}.c75Card.sel:after{content:'ВЫБРАНО';position:absolute;left:18px;top:18px;background:#fff;color:#111;border-radius:99px;padding:5px 7px;font:800 8px Arial}.c75Card em{top:17px!important;right:17px!important}.c75Quick button:before{content:'◌';margin-right:5px}.c75Quick button:first-child:before{content:'★'}
@media(max-width:520px){#catalog7500{margin-left:-2px;margin-right:-2px;padding:12px;border-radius:18px}.c75Head b{font-size:21px!important}.c75Head span{font-size:16px!important}.c75Guide{display:block}.c75Guide span{display:block;margin-top:4px;line-height:1.35}.c75Grid{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important}.c75Card{min-height:190px!important;padding:8px!important;border-radius:14px!important}.c75Visual{height:88px!important;margin-bottom:9px!important}.c75Card>b{font-size:12px!important}.c75Card small strong{font-size:9px}.c75Card small span{font-size:8px}.c75Card em{font-size:6px!important;top:12px!important;right:12px!important}.c75Card.sel:after{font-size:6px;left:12px;top:12px}.c75Quick{margin-left:-12px;margin-right:-12px;padding-left:12px!important;padding-right:12px!important}}
`;document.head.appendChild(css);
}
['heroCreate','newBtn','smartStart'].forEach(id=>document.getElementById(id)?.addEventListener('click',()=>setTimeout(enhance,650)));document.getElementById('bizGrid')?.addEventListener('click',()=>setTimeout(enhance,650));setTimeout(enhance,900);
})();