/* CLIENTA QA pass 18: exactly 7,500 original responsive design presets. 25 architectures × 30 visual palettes × 10 typography systems. */
(function(){
const ARCH=[
['Editorial Hero','editorial luxury magazine serif',0],['Swiss Grid','minimal swiss clean grid',1],['Bento Commerce','bento cards commerce app',2],['Immersive Story','immersive story visual premium',3],['Split Luxury','split luxury premium editorial',4],['Catalog Pro','catalog services corporate dense',5],['Performance','automotive sport performance dark',6],['Glass Future','glass tech digital gradient',7],['Brutal Type','brutal typography bold experimental',8],['Compact App','compact app mobile product',9],
['Gallery Mosaic','gallery portfolio image creative',2],['Poster Hero','poster huge type bold',8],['Soft Cards','soft rounded wellness beauty',2],['Quiet Luxury','quiet luxury whitespace editorial',0],['Dashboard','dashboard metrics business saas',9],['Marketplace','marketplace catalog cards commerce',5],['Timeline Story','timeline story narrative editorial',3],['Studio Portfolio','studio portfolio creative gallery',4],['Neo Banking','fintech banking clean product',1],['Hospitality','hotel restaurant hospitality editorial',0],['Medical Trust','medical clinic clean trustworthy',1],['Auto Configurator','automotive configurator dark technical',6],['Restaurant Menu','food menu restaurant editorial',5],['Beauty Booking','beauty booking soft premium',2],['Agency Experimental','agency experimental brutal creative',8]
];
const PAL=[
['Obsidian','dark black luxury',10],['Ivory','ivory editorial warm',11],['Pearl','pearl beauty light',12],['Noir','noir dark editorial',13],['Champagne','champagne luxury warm',14],['Neo Blue','blue tech saas',15],['Neo Lime','lime bold tech',16],['Cloud','cloud minimal clean',17],['Pill','soft app rounded',18],['Midnight','midnight gradient tech',19],['Blush','blush beauty pink',20],['Milk Rose','rose beauty soft',21],['Lavender','lavender wellness soft',22],['Beauty Editorial','beauty beige editorial',23],['Soft Mono','mono swiss minimal',24],['Track Black','automotive sport dark',25],['Carbon','automotive industrial dark',26],['Electric','electric neon tech',27],['Titanium','industrial clean metallic',28],['Racing','red sport automotive',29],['Clinic White','medical white clean',30],['Calm Blue','medical blue calm',31],['Mint Care','medical mint wellness',32],['Dental Pearl','dental clean blue',33],['Clinical Mono','clinical minimal white',34],['Bistro','food warm restaurant',35],['Olive','organic food natural',36],['Wine','wine luxury restaurant dark',37],['Cafe Cream','cafe warm editorial',38],['Sushi Dark','food japanese dark',39]
];
const TYPE=[
['Modern Sans','modern sans clean',5],['Swiss','swiss grotesk minimal',6],['Editorial Serif','editorial serif luxury',10],['Luxury Serif','luxury serif classic',9],['Grotesk','grotesk bold modern',15],['Humanist','humanist soft friendly',12],['Tech','tech geometric digital',8],['Mono Accent','mono technical brutal',14],['Display Bold','display bold creative',16],['Balanced','balanced corporate readable',7]
];
const NICHE={
'Детейлинг':['automotive','performance','carbon','dark','technical'],'Автосервис':['automotive','catalog','technical','industrial'],'Тюнинг-ателье':['automotive','sport','experimental','dark'],'Барбершоп':['luxury','dark','editorial','bold'],'Салон красоты':['beauty','soft','luxury','editorial'],'Маникюр':['beauty','soft','pink','booking'],'Стоматология':['medical','clean','trust','dental'],'Клиника':['medical','clean','trust','corporate'],'Ресторан':['restaurant','food','hospitality','editorial'],'Кафе':['cafe','food','warm','organic'],'Фитнес-клуб':['sport','bold','performance','dark'],'Йога-студия':['wellness','soft','organic','quiet'],'Фотограф':['portfolio','gallery','editorial','creative'],'Видеограф':['portfolio','immersive','dark','creative'],'Маркетинговое агентство':['agency','experimental','brutal','creative'],'IT-студия':['tech','saas','product','bento'],'Риелтор':['luxury','corporate','editorial','clean'],'Аренда апартаментов':['hospitality','luxury','editorial','warm'],'Юрист':['corporate','trust','quiet','luxury'],'Бухгалтер':['corporate','clean','dashboard','trust'],'Онлайн-школа':['app','cards','clean','friendly'],'Груминг':['soft','friendly','cards','warm']
};
const TOTAL=ARCH.length*PAL.length*TYPE.length; // 25*30*10 = 7500
function preset(id){id=Math.max(0,Math.min(TOTAL-1,+id||0));const t=id%TYPE.length,p=Math.floor(id/TYPE.length)%PAL.length,a=Math.floor(id/(TYPE.length*PAL.length));return{id,a,p,t,arch:ARCH[a],pal:PAL[p],type:TYPE[t],name:`${ARCH[a][0]} · ${PAL[p][0]} · ${TYPE[t][0]}`,tags:`${ARCH[a][1]} ${PAL[p][1]} ${TYPE[t][1]}`};}
function nicheScore(x,biz){const ws=NICHE[biz]||[];return ws.reduce((s,w)=>s+(x.tags.includes(w)?2:0),0);}
function apply(x){if(typeof st==='undefined')return;st.layout=x.arch[2];st.theme=x.pal[2];st.font=x.type[2];st.design7500=x.id;st.designArch=x.a;try{renderThemes?.();renderFonts?.();renderPreview?.();}catch(e){}localStorage.setItem('clienta_design7500',String(x.id));}
const oldNorm=typeof normalizeProject==='function'?normalizeProject:null;if(oldNorm)normalizeProject=function(p={}){const n=oldNorm(p);n.design7500=p.design7500??n.design7500??st?.design7500??null;n.designArch=p.designArch??n.designArch??st?.designArch??null;return n};
const oldClient=typeof clientMarkup==='function'?clientMarkup:null;if(oldClient)clientMarkup=function(input,interactive=true){const p=normalizeProject(input);let h=oldClient(p,interactive);if(p.designArch!=null)h=h.replace('class="public','class="public arch7500-'+p.designArch);return h};
function mount(){const s2=document.getElementById('s2');if(!s2||document.getElementById('catalog7500'))return;const root=document.createElement('section');root.id='catalog7500';root.innerHTML=`<div class="c75Head"><div><b>7 500 дизайнов</b><small>Авторские responsive-пресеты CLIENTA</small></div><span id="c75Count">7500</span></div><input id="c75Search" class="field" placeholder="Найти: luxury, тёмный, медицинский, авто, editorial, bento…"><div id="c75Quick" class="c75Quick"></div><div id="c75Grid" class="c75Grid"></div><button id="c75More" type="button" class="c75More">Показать ещё</button>`;document.getElementById('themes')?.parentNode?.insertBefore(root,document.getElementById('themes'));
const quick=['Рекомендуем','Luxury','Minimal','Dark','Editorial','Bento','Gallery','Tech','Brutal','Beauty','Medical','Auto','Food','Corporate'];document.getElementById('c75Quick').innerHTML=quick.map(x=>`<button data-q="${x.toLowerCase()}">${x}</button>`).join('');let q='',limit=60;
function norm(s){return(s||'').toLowerCase().replace('рекомендуем','').replace('лакшери','luxury').replace('тёмный','dark').replace('темный','dark').replace('минимализм','minimal').replace('медицинский','medical').replace('авто','automotive').replace('еда','food').replace('красота','beauty').replace('брутальный','brutal');}
function results(){const biz=st?.biz||'';let arr=[];for(let i=0;i<TOTAL;i++){const x=preset(i);const sc=nicheScore(x,biz);if(!q||x.name.toLowerCase().includes(q)||x.tags.includes(q)||q==='рекомендуем'||q.split(/\s+/).every(w=>x.tags.includes(w)))arr.push([x,sc]);}if(q==='рекомендуем'||!q)arr.sort((a,b)=>b[1]-a[1]);return arr;}
function draw(reset=false){if(reset)limit=60;const arr=results();document.getElementById('c75Count').textContent=arr.length.toLocaleString('ru-RU');document.getElementById('c75Grid').innerHTML=arr.slice(0,limit).map(([x,sc])=>`<button class="c75Card ${sc>=6?'top':''}" data-id="${x.id}"><i class="sw" style="--c:${typeof THEMES!=='undefined'&&THEMES[x.pal[2]]?THEMES[x.pal[2]].ac:'#111'}"></i><b>${x.name}</b><small>${x.tags.split(' ').slice(0,6).join(' · ')}</small>${sc>=6?'<em>ТОП ДЛЯ НИШИ</em>':''}</button>`).join('');document.getElementById('c75More').style.display=limit<arr.length?'block':'none';document.querySelectorAll('.c75Card').forEach(b=>b.onclick=()=>{const x=preset(b.dataset.id);apply(x);document.querySelectorAll('.c75Card.sel').forEach(z=>z.classList.remove('sel'));b.classList.add('sel');});}
document.getElementById('c75Search').oninput=e=>{q=norm(e.target.value.trim());draw(true)};document.getElementById('c75Quick').onclick=e=>{const b=e.target.closest('[data-q]');if(!b)return;q=norm(b.dataset.q);document.getElementById('c75Search').value=b.dataset.q==='рекомендуем'?'Рекомендуем':b.dataset.q;draw(true)};document.getElementById('c75More').onclick=()=>{limit+=60;draw(false)};draw(true);}
const css=document.createElement('style');css.textContent=`#catalog7500{margin:18px 0 24px}.c75Head{display:flex;justify-content:space-between;align-items:end;margin-bottom:10px}.c75Head b{display:block;font-size:20px}.c75Head small{display:block;color:#777;margin-top:3px}.c75Head span{font-weight:900;font-size:22px}.c75Quick{display:flex;gap:7px;overflow:auto;padding:8px 0 12px;scrollbar-width:none}.c75Quick button,.c75More{border:1px solid #ddd;background:#fff;border-radius:999px;padding:9px 12px;font-weight:800;white-space:nowrap}.c75Grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.c75Card{position:relative;text-align:left;min-height:128px;padding:15px;border:1px solid #ddd;border-radius:18px;background:#fff;overflow:hidden}.c75Card .sw{display:block;width:34px;height:8px;border-radius:99px;background:var(--c);margin-bottom:20px}.c75Card b{display:block;font-size:14px;line-height:1.2}.c75Card small{display:block;color:#777;margin-top:8px;font-size:10px;line-height:1.35}.c75Card em{position:absolute;right:7px;top:7px;background:#111;color:#fff;padding:5px 6px;border-radius:999px;font:800 7px/1 Arial;font-style:normal}.c75Card.sel{outline:3px solid #111}.c75More{display:block;margin:14px auto}.public[class*="arch7500-"] .service,.public[class*="arch7500-"] .feature{transition:.2s transform}.public.arch7500-2 .services,.public.arch7500-10 .services,.public.arch7500-14 .features{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.public.arch7500-3 .services,.public.arch7500-16 .services{display:flex;overflow:auto;scroll-snap-type:x mandatory;gap:12px}.public.arch7500-3 .service,.public.arch7500-16 .service{min-width:78%;scroll-snap-align:start}.public.arch7500-5 .service,.public.arch7500-15 .service,.public.arch7500-22 .service{border-radius:4px!important}.public.arch7500-8 .service,.public.arch7500-11 .service,.public.arch7500-24 .service{border:2px solid currentColor!important;border-radius:0!important}.public.arch7500-13 .service{box-shadow:none!important;border-color:transparent!important}.public.arch7500-20 .service{border-radius:14px!important}.public.arch7500-21 .hero{min-height:48vh}.public.arch7500-23 .service{border-radius:28px!important}@media(max-width:900px){.c75Grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.c75Grid{grid-template-columns:1fr}.c75Card{min-height:108px}.public.arch7500-2 .services,.public.arch7500-10 .services,.public.arch7500-14 .features{grid-template-columns:1fr}.public[class*="arch7500-"]{overflow-x:hidden}.public[class*="arch7500-"] h1,.public[class*="arch7500-"] h2{overflow-wrap:anywhere}}`;document.head.appendChild(css);
['heroCreate','newBtn','smartStart'].forEach(id=>document.getElementById(id)?.addEventListener('click',()=>setTimeout(mount,100)));document.getElementById('bizGrid')?.addEventListener('click',()=>setTimeout(mount,100));setTimeout(mount,500);window.CLIENTA_7500={total:TOTAL,preset,architectures:ARCH,palettes:PAL,typography:TYPE};
})();